services:
  - type: web
    name: placementai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        sync: false        # means Render will prompt you to enter the value manually
      - key: SECRET_KEY
        sync: false